### ISSUE TITLE
3D Tiles Tools roadmap

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles-tools#1]
More ideas to come...

# Tools

**Definitely**

* [ ] Fusion: Merge tileset with external tileset.json references into one tileset.json
* [ ] Fission: Separate a monolithic tileset.json into several tileset.json based on different criteria: e.g., `n` tiles per tileset.json, `m` levels per tileset.json, etc.
* [ ] Generate stats like [gltf-statistics](https://github.com/AnalyticalGraphicsInc/gltf-statistics).

**As Needed**

* [ ] Visualize a tileset's spatial data structure, perhaps even an interactive tileset explorer using Cesium with D3 overlay
* [ ] Separate composites, i.e., separate a composite tile into several tiles
   * [ ] Separate out into separate tilesets if useful, e.g., one for buildings, one for trees, etc.
   * [ ] Combine tiles into composites
* [ ] Merge multiple tilesets into one tileset

# Validator

* [ ] Detailed list TBA
* [ ] Integrate [glTF Validator](https://github.com/KhronosGroup/glTF-Validator) for `b3dm` and `i3dm` tile formats
